name: Language
main: Language\Language
version: 1.0.0
author: SharpyKurth
api:
 - 3.3.1
 - 3.3.4
load: STARTUP
commands:
  language:
    description: change your language
    permission: default
    usage: /language list
